package com.myspace.job_portal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Position")
	private java.lang.String position;
	@org.kie.api.definition.type.Label(value = "Candidate")
	private com.myspace.job_portal.Candidate candidate;

	public Application() {
	}

	public java.lang.String getPosition() {
		return this.position;
	}

	public void setPosition(java.lang.String position) {
		this.position = position;
	}

	public com.myspace.job_portal.Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(com.myspace.job_portal.Candidate candidate) {
		this.candidate = candidate;
	}

	public Application(java.lang.String position,
			com.myspace.job_portal.Candidate candidate) {
		this.position = position;
		this.candidate = candidate;
	}
    
    @Override
    public String toString() {
        return "Position: " + position + "\nCandidate: " + candidate.toString();
    }
 
}