package com.myspace.job_portal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Candidate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Date of Birth")
	private java.time.LocalDate dob;
	@org.kie.api.definition.type.Label(value = "E-mail")
	private java.lang.String email;
	@org.kie.api.definition.type.Label(value = "Gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label(value = "Grade Point Average")
	private float gpa;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "University")
	private java.lang.String university;

	public Candidate() {
	}

	public java.time.LocalDate getDob() {
		return this.dob;
	}

	public void setDob(java.time.LocalDate dob) {
		this.dob = dob;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public float getGpa() {
		return this.gpa;
	}

	public void setGpa(float gpa) {
		this.gpa = gpa;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getUniversity() {
		return this.university;
	}

	public void setUniversity(java.lang.String university) {
		this.university = university;
	}

	public Candidate(java.time.LocalDate dob, java.lang.String email,
			java.lang.String gender, float gpa, java.lang.String name,
			java.lang.String university) {
		this.dob = dob;
		this.email = email;
		this.gender = gender;
		this.gpa = gpa;
		this.name = name;
		this.university = university;
	}
	
	@Override
	public String toString() {
	    return this.name + " " + this.dob + " " + this.gender + " " + this.email + " " + this.gpa + " " + this.university;
	}

}