package com.myspace.job_portal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Interview implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Interviewer")
	private java.lang.String interviewer;
	@org.kie.api.definition.type.Label("Candidate")
	private java.lang.String candidate;

	@org.kie.api.definition.type.Label(value = "Date and Time")
	private java.time.LocalDateTime dateTime;

	public Interview() {
	}

	public java.lang.String getInterviewer() {
		return this.interviewer;
	}

	public void setInterviewer(java.lang.String interviewer) {
		this.interviewer = interviewer;
	}

	public java.lang.String getCandidate() {
		return this.candidate;
	}

	public void setCandidate(java.lang.String candidate) {
		this.candidate = candidate;
	}

	public java.time.LocalDateTime getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(java.time.LocalDateTime dateTime) {
		this.dateTime = dateTime;
	}

	public Interview(java.lang.String interviewer, java.lang.String candidate,
			java.time.LocalDateTime dateTime) {
		this.interviewer = interviewer;
		this.candidate = candidate;
		this.dateTime = dateTime;
	}

    @Override
    public String toString() {
        return "Interviewer: " + interviewer + "\n" +
            "Candidate: " + candidate + "\n" +
            "Date and Time: " + dateTime;
    }

}