package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Candidate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("E-mail")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Gender")
	private java.lang.String gender;
	@org.kie.api.definition.type.Label("Grade Point Average")
	private float gpa;
	@org.kie.api.definition.type.Label("University")
	private java.lang.String university;

	@org.kie.api.definition.type.Label("Date of Birth")
	private String dob;

	public Candidate() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public float getGpa() {
		return this.gpa;
	}

	public void setGpa(float gpa) {
		this.gpa = gpa;
	}

	public java.lang.String getUniversity() {
		return this.university;
	}

	public void setUniversity(java.lang.String university) {
		this.university = university;
	}

	@Override
	public String toString() {
		return "Name: " + name + "\n" + "E-mail: " + email + "\n" + "Gender: "
				+ gender + "\n" + "Grade Point Average: " + gpa + "\n"
				+ "University: " + university + "\n" + "Date of Birth: " + dob;
	}

	public java.lang.String getDob() {
		return this.dob;
	}

	public void setDob(java.lang.String dob) {
		this.dob = dob;
	}

	public Candidate(java.lang.String name, java.lang.String email,
			java.lang.String gender, float gpa, java.lang.String university,
			java.lang.String dob) {
		this.name = name;
		this.email = email;
		this.gender = gender;
		this.gpa = gpa;
		this.university = university;
		this.dob = dob;
	}

}