package com.myspace.job_portal;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Interview implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Interview Date and Time")
	private java.time.LocalDateTime interviewDateTime;
	@org.kie.api.definition.type.Label(value = "Interviewer")
	private java.lang.String interviewer;

	public Interview() {
	}

	public java.time.LocalDateTime getInterviewDateTime() {
		return this.interviewDateTime;
	}

	public void setInterviewDateTime(java.time.LocalDateTime interviewDateTime) {
		this.interviewDateTime = interviewDateTime;
	}

	public java.lang.String getInterviewer() {
		return this.interviewer;
	}

	public void setInterviewer(java.lang.String interviewer) {
		this.interviewer = interviewer;
	}

	public Interview(java.time.LocalDateTime interviewDateTime,
			java.lang.String interviewer) {
		this.interviewDateTime = interviewDateTime;
		this.interviewer = interviewer;
	}
	
	@Override
	public String toString() {
		return this.interviewDateTime + "\n" + this.interviewer + "\n";
	}

}